export const addObjectFields = [
    {
      label: "Name of a data collector",
      name: "collector_name",
      type: "text",
      placeholder: "Enter collector name",
      errorMessage: "collector name is required",
      disabled: false,
    },
    {
      label: "Date of birth",
      name: "dob",
      type: "text",
      placeholder: "Enter municipality",
      errorMessage: "Municipality is required",
      disabled: false,
    },
    {
      label: "Enter age",
      name: "age",
      type: "text",
      placeholder: "Enter population details",
      errorMessage: "Population details is required",
      disabled: false,
    },
    {
      label: "Select gender",
      name: "gender",
      type: "select",
      placeholder: "Select gender",
      errorMessage: "gender is required",
      disabled: false,
    },
    {
      label: "Phone number",
      name: "phone",
      type: "text",
      placeholder: "Enter phone number",
      errorMessage: "Phone is required",
      disabled: false,
    },
    // {
    //   label: "Email ID",
    //   name: "collector_email",
    //   type: "text",
    //   placeholder: "Enter email",
    //   errorMessage: "Email is required",
    //   disabled: false,
    // },
    // {
    //     label: "Address",
    //     name: "address",
    //     type: "textarea",
    //     placeholder: "Enter Address",
    //     errorMessage: "Address is required",
    //     disabled: false,
    //   },
  ];