export const addObjectFields = [
    {
      label: "Name of a data reviewer",
      name: "first_name",
      type: "text",
      placeholder: "Enter reviewer name",
      errorMessage: "This field is required",
      disabled: false,
    },
    {
      label: "Date of birth",
      name: "dob",
      type: "date",
      format:'YYYY-MM-DD',
      placeholder: "Enter Date of birth",
      errorMessage: "This field is required",
      disabled: false,
    },
    {
      label: "Select gender",
      name: "gender",
      type: "select",
      placeholder: "Select gender",
      errorMessage: "This field is required",
      disabled: false,
    },
    {
      label: "Phone number",
      name: "phone_no",
      type: "text",
      placeholder: "Enter phone number",
      errorMessage: "This field is required",
      disabled: false,
    },
     {
      label: "Email ID",
      name: "email",
      type: "text",
      placeholder: "Enter email",
      errorMessage: "This field is required",
      disabled: false,
    },
    {
      label: "Assign Reviewer ID",
      name: "official_number",
      type: "text",
      placeholder: "Enter Reviewer ID",
      errorMessage: "This field is required",
      disabled: false,
    },   
    {
        label: "Address",
        name: "address",
        type: "textarea",
        placeholder: "Enter Address",
        errorMessage: "This field is required",
        disabled: false,
      },
      {
        name: "barangay_id",
        label: "Assign Barangay ",
        type: "text",
        placeholder: "Select from list",
        errorMessage: "This field is required",
        disabled: false,
      },
  ];