export const addObjectFields = [
  {
    label: "Barangay Name",
    name: "barangay_name",
    type: "text",
    placeholder: "Enter barangay name",
    errorMessage: "Barangay name is required",
    disabled: false,
  },
  {
    label: "Municipality",
    name: "municipality",
    type: "text",
    placeholder: "Enter municipality",
    errorMessage: "Municipality is required",
    disabled: false,
  },
  {
    label: "Population Details",
    name: "population_details",
    type: "text",
    placeholder: "Enter population details",
    errorMessage: "Population details is required",
    disabled: false,
  },
  {
    label: "Barangay Captain",
    name: "barangay_captain",
    type: "text",
    placeholder: "Enter barangay captain",
    errorMessage: "Barangay captain is required",
    disabled: false,
  },
  {
    label: "Number of Data Collectors",
    name: "numberof_data_collectors",
    type: "text",
    placeholder: "Enter number of data collectors",
    errorMessage: "Number of data collectors is required",
    disabled: false,
  },
  {
    label: "Number of Data Reviewers",
    name: "numberof_data_reviewers",
    type: "number",
    placeholder: "Enter number of data reviewers",
    errorMessage: "Number of data reviewers is required",
    disabled: false,
  },
];
